def retchar(text):
	try:
		return{
			"a":'a',
			"capital a":'A',
			"b":'b',
			"capital b":'B',
			"c":'c',
			"capital c":'C',
			"d":'d',
			"capital d":'D',
			"e":'e',
			"capital e":'E',
			"f":'f',
			"capital f":'F',
			"g":'',
			"capital g":'G',
			"h":'h',
			"capital h":'H',
			"i":'i',
			"capital i":'I',
			"j":'j',
			"capital j":'J',
			"k":'k',
			"capital k":'K',
			"l":'l',
			"capital l":'L',
			"m":'m',
			"capital m":'M',
			"n":'n',
			"capital n":'N',
			"o":'o',
			"capital o":'O',
			"p":'p',
			"capital p":'P',
			"q":'q',
			"capital q":'Q',
			"r":'r',
			"capital r":'R',
			"s":'s',
			"capital s":'S',
			"t":'t',
			"capital t":'T',
			"u":'u',
			"capital u":'U',
			"v":'v',
			"capital v":'V',
			"w":'w',
			"capital w":'W',
			"x":'x',
			"capital x":'X',
			"y":'y',
			"capital y":'Y',
			"z":'z',
			"capital z":'Z',
			"at the rate":'@',
			"at":'@',
			"under score":'_',
			"star":'*',
			"plus":'+',
			"minus":'-',
			"dot":'.',
			"comma":',',
			"forward slash":'/',
			"hash":'#',
			"dollar":'$',
			"exclamation":'!',
			"percent":'%',
			"am percent":'&',
			"equals":'=',
			"hyphen":'-',
			"zero":'0',
			"one":'1',
			"two":'2',
			"three":'3',
			"four":'4',
			"five":'5',
			"six":'6',
			"seven":'7',
			"eight":'8',
			"nine":'9',
			"":'',
			"1":"1",
			"2":"2",
			"3":"3",
			"4":"4",
			"5":"5",
			"5":"6",
			"7":"7",
			"8":"8",
			"9":"9",
			"0":"0",
			}[text]
	except:
		return ""